version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000
    env_file:
      - stagingenv.file
      - secrets.file
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`worthtrust.localhost`)"
    networks:
        - traefik

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - stagingenv.file
      - secrets.file
    expose:
      - 5432
    networks:
      - traefik
  
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cloudbeaver.entrypoints=web"
        - "traefik.http.routers.cloudbeaver.rule=Host(`cloudbeaver.localhost`)"
        - "traefik.http.services.cloudbeaver.loadbalancer.server.port=8978"
    volumes:
        - cloudbeaver:/var/lib/cloudbeaver
    networks:
      - traefik

  traefik:
    image: traefik:v2.9.6
    ports:
        # web exposed on 8008, cloudbeaver exposed on 8978, traefik dashboard exposed on 8081
        - 80:80
        - 8008:80
        - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
        - traefik

networks:
  traefik:

volumes:
  postgres_data:
  cloudbeaver: