
name: WORTH TRUST BE CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup up Python
      uses: actions/setup-python@v3
    - name: Ruff
      uses: chartboost/ruff-action@v1
      with:
        src: "./src"
        version: 0.0.259
        args: --select B
    - name: Black formatter
      uses: rickstaa/action-black@v1
      with:
        black_args: ". --check"

  CI:
    needs: pre-commit
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

      # Install python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
      # Install VENV
    - name: Install Python Virtual ENV
      run: pip3 install virtualenv
      # Set env if does not exist yet
    - name: Set up virtual ENV
      uses: actions/cache@v2
      id: cache-venv
      with:
        path: venv
        key: ${{runner.os}}-venv-${{hashFiles('**/requirements.txt')}}
        restore-keys: /
          ${{runner.os}}
    
      # Build a Virtual ENV, but only if it doesn't already exist
    - name: Activate Virtual ENV
      run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Ruff
      uses: chartboost/ruff-action@v1
      with:
        src: "./src"
        version: 0.0.259
        args: --select B

    # - name: runner / black formatter
    #   uses: rickstaa/action-black@v1
    #   with:
    #     black_args: ". --check"

      # UNIT TESTS
      #TODO: Integrate unit tests
      # - name: Run Tests   
      #   # Note that you have to activate the virtualenv in every step
      #   # because GitHub actions doesn't preserve the environment   
      #   run: . venv/bin/activate && pytest
