
name: WORTH TRUST BE CI

on:
  push:
    branches: [ "main", "master", "dev"]
  pull_request:
    branches: [ "main", "master", "dev"]

permissions:
  contents: read


jobs:
  PRE-COMMIT:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        # Ruff
      - name: Ruff linting
        uses: chartboost/ruff-action@v1
        with:
          args: --fix --show-fixes --verbose
          src: "."
        # Black
      - name: Black formatting
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."

  CI:
    needs: PRE-COMMIT
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    timeout-minutes: 3200

    env:
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      DB_PSW: ${{secrets.DB_PSW}}
      EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
      EMAIL_USERNAME: ${{secrets.EMAIL_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}

      run: chmod +x initenv.sh && ./initenv.sh && echo "Composed .env file:" && cat .env

      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15-alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTRES_DB: postgres
        ports:
          # Maps tcp port DB_PORT on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

      # Install python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
      # Install VENV
    - name: Install Python Virtual ENV
      run: pip3 install virtualenv
      # Set env if does not exist yet
    - name: Set up virtual ENV
      uses: actions/cache@v2
      id: cache-venv
      with:
        path: venv
        key: ${{runner.os}}-venv-${{hashFiles('**/requirements.txt')}}
        restore-keys: /
          ${{runner.os}}
    
      # Build a Virtual ENV, but only if it doesn't already exist
    - name: Activate Virtual ENV
      run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'
        
      # Run tests
    - name: Run Tests
      run: . venv/bin/activate && pytest
